### ISSUE TITLE
 Add support for Go language

### ISSUE THREAD

**Issue by vnbrs** [vnbrs/eudc#1]
`eudc` manages different languages by modules, that can be found in the [`language` folder](https://github.com/vnbrs/eudc/tree/master/language). It would be nice to extend the languages with [Golang](https://golang.org).

Just as the JavaScript module:

```
class JavaScriptLanguage:
    name = 'JavaScript'
    extension = 'js'
    debugging_calls = [
        r'debugger',
        r'console\.log',
    ]
```

the Golang one should contain the debugging calls regular expression for Go.

Also, the `FILE_TYPES` constant should be extended to include Golang.
https://github.com/vnbrs/eudc/blob/2a42649e5e786e239e0762812cfe2d2bbd19f409/udce.py#L6

**Comment by jr7square** [comment]
Cool, let me give this a shot.
