### ISSUE TITLE
Add color to the CLI output

### ISSUE THREAD

**Issue by vnbrs** [vnbrs/eudc#2]
`eudc` output is not colored. It'd be nice to color the output. Every output is defined inside `udce.py` file on `click.echo` calls.

https://github.com/vnbrs/eudc/blob/e522c56c52d2ade29d3cf6db619e544b6e7d12e8/udce.py#L32

**Comment by ming060** [comment]
SImply add color to this output? What color would you like to add to this output?

**Comment by vnbrs** [comment]
> SImply add color to this output? What color would you like to add to this output?

Simply as that! I think it'd be nice to color the file and the line number in different colors.

**Comment by ming060** [comment]
OK, I will try to do this.
